BD = [
    {"INTELIGENCIA" : "INTRAPESSOAL", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 5,
      "CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE" : 5,
      "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 2,
      "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 2,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 2,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 2,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 2,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 2}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "AUTO-REFLEXÃO, AUTO-DESCOBRIMENTO", "PROFISSOES" : "PSICÓLOGOS, FILÓSOFOS, ESCRITORES E SOCIÓLOGOS"},

    {"INTELIGENCIA" : "INTERPESSOAL", "CARACTERISTICAS" :
     {"EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 1,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 1,
      "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 1,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 5,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 1,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 2,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 2,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 3}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "CONTATO HUMANO, COMUNICAÇÃO, COOPERAÇÃO E TRABALHO EM EQUIPE", "PROFISSOES" : "PADRES, POLÍTICOS, JORNALISTAS, RELAÇÕES PÚBLICAS, PROFESSORES E TURISMÓLOGOS"},

    {"INTELIGENCIA" : "LOGICA-MATEMATICA", "CARACTERISTICAS" :
     {"ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS" : 5,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 1,
      "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA" : 5,
      "TENHO FACILIDADE PARA ENTENDER PADRÕES, RELAÇÕES E CONEXÕES EM DIFERENTES CONTEXTOS, SEJA NA MATEMÁTICA OU EM OUTRAS ÁREAS" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "NÚMEROS E LÓGICA", "PROFISSOES" : "MATEMÁTICOS, ENGENHEIROS, ESPECIALISTAS EM COMPUTAÇÃO, CONTADORES E ADMINISTRADORES"},

    {"INTELIGENCIA" : "LINGUISTICA", "CARACTERISTICAS" :
     {"GOSTO DE LER E APRENDER SOBRE UMA AMPLA VARIEDADE DE TÓPICOS" : 5,
      "EU TENHO FACILIDADE EM APRENDER E USAR NOVAS LÍNGUAS" : 5,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 5,
      "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA" : 2,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 3,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 3}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "PALAVRAS E LIGUAGEM", "PROFISSOES" : " JORNALISTAS, ESCRITORES, TRADUTORES, REVISORES E PALESTRANTES"},

    {"INTELIGENCIA" : "MUSICAL", "CARACTERISTICAS" :
     {"ADORO CANTAR E TOCAR INSTRUMENTOS MUSICAIS" : 5,
      "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES" : 1,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 2,
      "CONSIGO IDENTIFICAR OS INSTRUMENTOS E NOTAS MUSICAIS EM UMA MÚSICA COM FACILIDADE, É COMO SE FOSSE UMA LINGUAGEM PARA MIM" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "MÚSICAS, SONS E RITMOS", "PROFISSOES" : "MÚSICOS, CANTORES, COMPOSITORES E CRÍTICOS MUSICAIS"},

    {"INTELIGENCIA" : "NATURALISTA", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 1,
      "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES" : 5,
      "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES" : 2,
      "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 5,
      "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA" : 1,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "OBSERVAÇÃO, CLASSIFICAÇÃO, RELAÇÃO E CONEXÃO COM A NATUREZA", "PROFISSOES" : "BIÓLOGOS, GEÓLOGOS E VETERINÁRIOS"},

    {"INTELIGENCIA" : "CINESTESICA-CORPORAL", "CARACTERISTICAS" :
     {"GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA" : 5,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 5,
      "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "EXPERIÊNCIA FÍSICA E MOVIMENTO, TOQUE E SENSAÇÕES", "PROFISSOES" : "DANÇARINOS, ATLETAS, ARTESÃOS E EDUCADORES FÍSICOS"},

    {"INTELIGENCIA" : "EXISTENCIAL", "CARACTERISTICAS" :
     {"EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 5,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 1,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 5,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 5,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 1}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "AUTO-REFLEXÃO, AUTO-DESCOBRIMENTO", "PROFISSOES" : "FILÓSOFOS, PROFESSORES, PALESTRANTES, TEÓLOGOS"},

    {"INTELIGENCIA" : "ESPACIAL-VISUAL", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 1,
      "ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS" : 2,
      "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES" : 1,
      "GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA" : 1,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 1,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 2}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "IMAGENS, FORMAS, GRAVURAS E ESPAÇO TRIDIMENSIONAL", "PROFISSOES" : "ARQUITETOS, ENGENHEIROS, PILOTOS DE AVIÃO E DESIGNERS"},

    {"INTELIGENCIA" : "EMOCIONAL", "CARACTERISTICAS" :
     {"CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE" : 3,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 5,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "EXPRESSÃO, COMPREENDENDO E REGULANDO AS EMOÇÕES", "PROFISSOES" : "PSICÓLOGO, COACH, CONSELHEIRO, TERAPEUTA, ASSISTENTE SOCIAL"},
]

#ideia: fazer uma lista com as perguntas, depois percorrer elas e fazer uma forma
#       de conseguir passar esses valores para o BD principal
perguntas = [{"PERGUNTA" : "GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES"},
             {"PERGUNTA" : "CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE"},
             {"PERGUNTA" : "ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS"},
             {"PERGUNTA" : "GOSTO DE LER E APRENDER SOBRE UMA AMPLA VARIEDADE DE TÓPICOS"},
             {"PERGUNTA" : "ADORO CANTAR E TOCAR INSTRUMENTOS MUSICAIS"},
             {"PERGUNTA" : "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES"},
             {"PERGUNTA" : "GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA"},
             {"PERGUNTA" : "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES"},
             {"PERGUNTA" : "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS"},
             {"PERGUNTA" : "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM APRENDER E USAR NOVAS LÍNGUAS"},
             {"PERGUNTA" : "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA"},
             {"PERGUNTA" : "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS"},
             {"PERGUNTA" : "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA"},
             {"PERGUNTA" : "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS"},
             {"PERGUNTA" : "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA"},
             {"PERGUNTA" : "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA"},
             {"PERGUNTA" : "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO"},
             {"PERGUNTA" : "CONSIGO IDENTIFICAR OS INSTRUMENTOS E NOTAS MUSICAIS EM UMA MÚSICA COM FACILIDADE, É COMO SE FOSSE UMA LINGUAGEM PARA MIM"},
             {"PERGUNTA" : "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS"},
             {"PERGUNTA" : "TENHO FACILIDADE PARA ENTENDER PADRÕES, RELAÇÕES E CONEXÕES EM DIFERENTES CONTEXTOS, SEJA NA MATEMÁTICA OU EM OUTRAS ÁREAS"}
             ]

#ZERAR VALORES DE OCORRÊNCIAS
for i in BD:
      i["OCORRENCIAS"]=0
      i["PERCENTUAL"]=0
  
for pos2, i2 in enumerate(perguntas):
    print("-=" * 60)
    caracteristica = i2["PERGUNTA"]
    print(caracteristica)
    nivel = int(input("0/5: "))
    for pos,i in enumerate(BD):
        inteligencia=i["INTELIGENCIA"]
        caracteristicas=i["CARACTERISTICAS"]
        if (caracteristica in caracteristicas):
            i["OCORRENCIAS"]+=caracteristicas[caracteristica] * nivel
            print("A CARACTERISTICA: ",caracteristica," É CARACTERÍSTICA DA INTELIGENCIA: ",inteligencia, "\nPESO ATUAL: ", i["OCORRENCIAS"], "\n")
        
        
print("\nPONDERACOES")
for i in BD:
    print("\nINTELIGENCIA: ", i["INTELIGENCIA"], "OCORRENCIAS: ", i["OCORRENCIAS"])
    
#TOTALIZAR PESOS
for i in BD:
    caracteristicas = i["CARACTERISTICAS"]
    soma = 0
    media_ponderada = 0
    for j in caracteristicas:
        soma += caracteristicas[j]
    media_ponderada = i["OCORRENCIAS"] / soma
    i["PERCENTUAL"] = media_ponderada * 10
    
#ordenando a lista BD pelo valor dos percentuais
BD_ordenado = sorted(BD, key=lambda x: x["PERCENTUAL"], reverse=True)

# Mostrando os três maiores valores que correspondem suas possíveis inteligências
print("\n\nSeus resultados.")
for i in range(3):
    print("-=" * 60)
    print(BD_ordenado[i]["INTELIGENCIA"], ": %", format(BD_ordenado[i]["PERCENTUAL"], ".2f"))
    print("Informações sobre a inteligência:")
    print("Melhor forma de aprendizado: ", BD_ordenado[i]["APRENDIZADO"])
    print("Melhores profissões: ", BD_ordenado[i]["PROFISSOES"])
print("-=" * 60)
    
    

