import textwrap

BD = [
    {"INTELIGENCIA" : "INTRAPESSOAL", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 5,
      "CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE" : 5,
      "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 2,
      "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 2,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 2,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 2,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 2,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 2}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "AUTO-REFLEXÃO, AUTO-DESCOBRIMENTO", "PROFISSOES" : "PSICÓLOGOS, FILÓSOFOS, ESCRITORES E SOCIÓLOGOS",
     "DESCRICAO" : "ESTA INTELIGÊNCIA SE REFERE À CAPACIDADE DE ENTENDER E GERENCIAR SUAS PRÓPRIAS EMOÇÕES, DE ESTABELECER METAS E DE REFLETIR SOBRE SUAS PRÓPRIAS AÇÕES. SE VOCÊ TEM FACILIDADE EM ENTENDER AS PRÓPRIAS EMOÇÕES, EM LIDAR COM SITUAÇÕES DE ESTRESSE E DE CONFLITO INTERNO, EM ESTABELECER METAS E EM REFLETIR SOBRE SEUS PENSAMENTOS E AÇÕES, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA INTRAPERSONAL MAIS FORTE."},

    {"INTELIGENCIA" : "INTERPESSOAL", "CARACTERISTICAS" :
     {"EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 1,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 1,
      "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 1,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 5,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 1,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 2,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 2,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 3}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "CONTATO HUMANO, COMUNICAÇÃO, COOPERAÇÃO E TRABALHO EM EQUIPE", "PROFISSOES" : "PADRES, POLÍTICOS, JORNALISTAS, RELAÇÕES PÚBLICAS, PROFESSORES E TURISMÓLOGOS",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE RELACIONA COM A CAPACIDADE DE ENTENDER E SE COMUNICAR COM OUTRAS PESSOAS, DE ESTABELECER RELAÇÕES INTERPESSOAIS SAUDÁVEIS E DE LIDERAR EQUIPES. SE VOCÊ TEM FACILIDADE EM COMPREENDER AS EMOÇÕES E INTENÇÕES DAS OUTRAS PESSOAS, EM LIDAR COM CONFLITOS E EM TRABALHAR BEM EM EQUIPE, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA INTERPESSOAL MAIS FORTE."},

    {"INTELIGENCIA" : "LOGICA-MATEMATICA", "CARACTERISTICAS" :
     {"ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS" : 5,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 1,
      "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA" : 5,
      "TENHO FACILIDADE PARA ENTENDER PADRÕES, RELAÇÕES E CONEXÕES EM DIFERENTES CONTEXTOS, SEJA NA MATEMÁTICA OU EM OUTRAS ÁREAS" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "NÚMEROS E LÓGICA", "PROFISSOES" : "MATEMÁTICOS, ENGENHEIROS, ESPECIALISTAS EM COMPUTAÇÃO, CONTADORES E ADMINISTRADORES",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE RELACIONA COM A CAPACIDADE DE RACIOCINAR DE FORMA LÓGICA, RESOLVER PROBLEMAS MATEMÁTICOS E CIENTÍFICOS, E IDENTIFICAR PADRÕES E RELAÇÕES ENTRE IDEIAS. SE VOCÊ GOSTA DE RESOLVER PROBLEMAS MATEMÁTICOS, TEM INTERESSE EM ÁREAS COMO CIÊNCIAS EXATAS E ENGENHARIAS, E TEM FACILIDADE EM IDENTIFICAR LIGAÇÕES ENTRE IDEIAS E CONCEITOS, VOCÊ PODE TER UMA INTELIGÊNCIA LÓGICO-MATEMÁTICA MAIS FORTE."},

    {"INTELIGENCIA" : "LINGUISTICA", "CARACTERISTICAS" :
     {"GOSTO DE LER E APRENDER SOBRE UMA AMPLA VARIEDADE DE TÓPICOS" : 5,
      "EU TENHO FACILIDADE EM APRENDER E USAR NOVAS LÍNGUAS" : 5,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 5,
      "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA" : 2,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 3,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 3}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "PALAVRAS E LIGUAGEM", "PROFISSOES" : " JORNALISTAS, ESCRITORES, TRADUTORES, REVISORES E PALESTRANTES",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE REFERE À SUA CAPACIDADE DE USAR A LINGUAGEM DE FORMA EFICAZ, TANTO NA COMUNICAÇÃO VERBAL QUANTO ESCRITA. SE VOCÊ TEM FACILIDADE EM APRENDER NOVOS IDIOMAS, CONSEGUE SE EXPRESSAR BEM POR MEIO DA ESCRITA OU DA FALA, GOSTA DE LER E ESCREVER, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA LINGUÍSTICA MAIS FORTE."},

    {"INTELIGENCIA" : "MUSICAL", "CARACTERISTICAS" :
     {"ADORO CANTAR E TOCAR INSTRUMENTOS MUSICAIS" : 5,
      "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES" : 1,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 2,
      "CONSIGO IDENTIFICAR OS INSTRUMENTOS E NOTAS MUSICAIS EM UMA MÚSICA COM FACILIDADE, É COMO SE FOSSE UMA LINGUAGEM PARA MIM" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "MÚSICAS, SONS E RITMOS", "PROFISSOES" : "MÚSICOS, CANTORES, COMPOSITORES E CRÍTICOS MUSICAIS",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE RELACIONA COM A CAPACIDADE DE COMPREENDER, CRIAR E APRECIAR A MÚSICA. SE VOCÊ TEM FACILIDADE EM TOCAR UM INSTRUMENTO MUSICAL, CANTAR, RECONHECER DIFERENTES TONS E RITMOS MUSICAIS, OU GOSTA DE OUVIR MÚSICA, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA MUSICAL MAIS FORTE."},

    {"INTELIGENCIA" : "NATURALISTA", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 1,
      "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES" : 5,
      "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES" : 2,
      "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS" : 5,
      "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA" : 1,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "OBSERVAÇÃO, CLASSIFICAÇÃO, RELAÇÃO E CONEXÃO COM A NATUREZA", "PROFISSOES" : "BIÓLOGOS, GEÓLOGOS E VETERINÁRIOS",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE REFERE À CAPACIDADE DE OBSERVAR, IDENTIFICAR E CLASSIFICAR PADRÕES NA NATUREZA. SE VOCÊ TEM FACILIDADE EM IDENTIFICAR ESPÉCIES DE ANIMAIS E PLANTAS, EM RECONHECER PADRÕES CLIMÁTICOS E SAZONAIS, EM COMPREENDER AS RELAÇÕES ECOLÓGICAS E EM ENTENDER OS PROCESSOS NATURAIS, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA NATURALISTA MAIS FORTE. PESSOAS COM ESSA HABILIDADE TENDEM A TER UMA GRANDE PAIXÃO PELA NATUREZA E PELO MEIO AMBIENTE, E PODEM DESENVOLVER HABILIDADES COMO A BOTÂNICA, A ZOOLOGIA, A ECOLOGIA E OUTRAS CIÊNCIAS RELACIONADAS AO ESTUDO DA NATUREZA."},

    {"INTELIGENCIA" : "CINESTESICA-CORPORAL", "CARACTERISTICAS" :
     {"GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA" : 5,
      "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS" : 5,
      "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "EXPERIÊNCIA FÍSICA E MOVIMENTO, TOQUE E SENSAÇÕES", "PROFISSOES" : "DANÇARINOS, ATLETAS, ARTESÃOS E EDUCADORES FÍSICOS",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE REFERE À HABILIDADE DE USAR O CORPO DE FORMA COORDENADA, CONTROLAR MOVIMENTOS E MANIPULAR OBJETOS COM DESTREZA. SE VOCÊ TEM FACILIDADE EM PRATICAR ESPORTES, DANÇAR, FAZER ATIVIDADES QUE ENVOLVEM COORDENAÇÃO MOTORA, OU TEM FACILIDADE EM REALIZAR ATIVIDADES MANUAIS, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA CORPORAL-CINESTÉSICA MAIS FORTE."},

    {"INTELIGENCIA" : "EXISTENCIAL", "CARACTERISTICAS" :
     {"EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS" : 5,
      "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS" : 1,
      "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA" : 5,
      "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO" : 5,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 1}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "AUTO-REFLEXÃO, AUTO-DESCOBRIMENTO", "PROFISSOES" : "FILÓSOFOS, PROFESSORES, PALESTRANTES, TEÓLOGOS",
     "DESCRICAO" : "A INTELIGÊNCIA EXISTENCIAL REFLETE A CAPACIDADE DE REFLETIR SOBRE QUESTÕES FUNDAMENTAIS DA EXISTÊNCIA HUMANA, COMO VIDA, MORTE, SENTIDO DA VIDA E LIBERDADE. PESSOAS COM ESSA HABILIDADE TÊM UMA COMPREENSÃO MAIS PROFUNDA DAS QUESTÕES EXISTENCIAIS E TENDÊNCIA A BUSCAR SIGNIFICADO E PROPÓSITO NA VIDA POR MEIO DE FILOSOFIA, ESPIRITUALIDADE OU OUTRAS FORMAS DE BUSCA. ELES TAMBÉM SÃO MAIS CAPAZES DE LIDAR COM INCERTEZAS E SITUAÇÕES DESAFIADORAS. SE VOCÊ TEM FACILIDADE EM REFLETIR SOBRE ESSAS QUESTÕES, VOCÊ PODE TER UMA INTELIGÊNCIA EXISTENCIAL MAIS FORTE."},

    {"INTELIGENCIA" : "ESPACIAL-VISUAL", "CARACTERISTICAS" :
     {"GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES" : 1,
      "ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS" : 2,
      "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES" : 1,
      "GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA" : 1,
      "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS" : 1,
      "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA" : 2}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "IMAGENS, FORMAS, GRAVURAS E ESPAÇO TRIDIMENSIONAL", "PROFISSOES" : "ARQUITETOS, ENGENHEIROS, PILOTOS DE AVIÃO E DESIGNERS",
     "DESCRICAO" : "ESSA INTELIGÊNCIA SE REFERE À HABILIDADE DE PERCEBER E MANIPULAR IMAGENS MENTAIS, VISUALIZAR OBJETOS EM TRÊS DIMENSÕES E ENTENDER RELAÇÕES ESPACIAIS. SE VOCÊ GOSTA DE DESENHAR, DE TRABALHAR COM GRÁFICOS E DIAGRAMAS, TEM FACILIDADE EM ENTENDER MAPAS E PLANOS, E CONSEGUE IDENTIFICAR RAPIDAMENTE OBJETOS EM SEU AMBIENTE, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA ESPACIAL MAIS FORTE."},

    {"INTELIGENCIA" : "EMOCIONAL", "CARACTERISTICAS" :
     {"CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE" : 3,
      "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS" : 5,
      "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS" : 5}, "OCORRENCIAS" : 0, "PERCENTUAL" : 0,
     "APRENDIZADO" : "EXPRESSÃO, COMPREENDENDO E REGULANDO AS EMOÇÕES", "PROFISSOES" : "PSICÓLOGO, COACH, CONSELHEIRO, TERAPEUTA, ASSISTENTE SOCIAL",
     "DESCRICAO" : "A INTELIGÊNCIA EMOCIONAL SE REFERE À CAPACIDADE DE RECONHECER E GERENCIAR AS PRÓPRIAS EMOÇÕES E AS EMOÇÕES DOS OUTROS. PESSOAS COM ESSA HABILIDADE TENDEM A TER UMA MAIOR CONSCIÊNCIA EMOCIONAL, A LIDAR MELHOR COM SITUAÇÕES DE ESTRESSE E A ESTABELECER RELAÇÕES INTERPESSOAIS MAIS SAUDÁVEIS. ALÉM DISSO, ELAS COSTUMAM TER UMA MAIOR EMPATIA E HABILIDADE EM LIDAR COM CONFLITOS INTERPESSOAIS. SE VOCÊ TEM FACILIDADE EM ENTENDER E GERENCIAR SUAS EMOÇÕES, BEM COMO AS EMOÇÕES DOS OUTROS, ENTÃO VOCÊ PODE TER UMA INTELIGÊNCIA EMOCIONAL MAIS FORTE."},
]

#ideia: fazer uma lista com as perguntas, depois percorrer elas e fazer uma forma
#       de conseguir passar esses valores para o BD principal
perguntas = [{"PERGUNTA" : "GOSTO DE ESTAR SOZINHO PARA REFLETIR SOBRE MEUS PENSAMENTOS E EMOÇÕES"},
             {"PERGUNTA" : "CONSIGO IDENTIFICAR E NOMEAR MINHAS EMOÇÕES COM FACILIDADE"},
             {"PERGUNTA" : "ADORO RESOLVER PROBLEMAS LÓGICOS E MATEMÁTICOS"},
             {"PERGUNTA" : "GOSTO DE LER E APRENDER SOBRE UMA AMPLA VARIEDADE DE TÓPICOS"},
             {"PERGUNTA" : "ADORO CANTAR E TOCAR INSTRUMENTOS MUSICAIS"},
             {"PERGUNTA" : "GOSTO DE OBSERVAR A NATUREZA E APRENDER SOBRE DIFERENTES ESPÉCIES"},
             {"PERGUNTA" : "GOSTO DE PRATICAR ESPORTES E MANTER MEU CORPO EM FORMA"},
             {"PERGUNTA" : "EU GOSTO DE DESENHAR E APRECIO A BELEZA DAS FORMAS E CORES"},
             {"PERGUNTA" : "EU ME SINTO CONECTADO(A) COM A NATUREZA E APRECIO O CONTATO COM ANIMAIS E PLANTAS"},
             {"PERGUNTA" : "EU GOSTO DE ME EXPRESSAR ATRAVÉS DA DANÇA E MOVIMENTOS CORPORAIS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM APRENDER E USAR NOVAS LÍNGUAS"},
             {"PERGUNTA" : "EU GOSTO DE EXPLORAR NOVAS IDEIAS E REFLETIR SOBRE QUESTÕES FILOSÓFICAS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM RESOLVER PROBLEMAS QUE ENVOLVEM O USO DO CORPO E COORDENAÇÃO MOTORA"},
             {"PERGUNTA" : "EU GOSTO DE LIDERAR E TRABALHAR EM EQUIPE PARA ALCANÇAR OBJETIVOS COMUNS"},
             {"PERGUNTA" : "EU GOSTO DE LER E ESCREVER TEXTOS CRIATIVOS E/OU PERSUASIVOS"},
             {"PERGUNTA" : "EU TENHO FACILIDADE EM IDENTIFICAR E CATEGORIZAR ELEMENTOS DA NATUREZA"},
             {"PERGUNTA" : "EU ME SINTO CONFORTÁVEL EM SITUAÇÕES QUE ENVOLVEM ALTAS EMOÇÕES E/OU RISCOS"},
             {"PERGUNTA" : "SEMPRE PROCURO ENTENDER A LÓGICA POR TRÁS DOS SISTEMAS E PROCESSOS QUE ENCONTRO NO MEU DIA A DIA"},
             {"PERGUNTA" : "GOSTO DE REFLETIR SOBRE A NATUREZA DA EXISTÊNCIA HUMANA E O SENTIDO DA VIDA"},
             {"PERGUNTA" : "ACREDITO QUE A VIDA É UM PROCESSO CONSTANTE DE BUSCA POR SIGNIFICADO E PROPÓSITO"},
             {"PERGUNTA" : "CONSIGO IDENTIFICAR OS INSTRUMENTOS E NOTAS MUSICAIS EM UMA MÚSICA COM FACILIDADE, É COMO SE FOSSE UMA LINGUAGEM PARA MIM"},
             {"PERGUNTA" : "SOU CAPAZ DE COMPREENDER E ACOLHER AS EMOÇÕES DOS OUTROS, AJUDANDO-OS A SE SENTIR MAIS CONFORTÁVEIS E SEGUROS"},
             {"PERGUNTA" : "TENHO FACILIDADE PARA ENTENDER PADRÕES, RELAÇÕES E CONEXÕES EM DIFERENTES CONTEXTOS, SEJA NA MATEMÁTICA OU EM OUTRAS ÁREAS"}
             ]

def quebra_linhas(frase, largura=133):
    linhas = textwrap.wrap(frase, width=largura)
    for linha in linhas:
        print(linha)

def cabecalho():
    tam = 133
    txt1 = 'Bem vindo ao sistema de Avaliação das Múltiplas Inteligências'
    txt2 = 'Esse teste é baseado na teoria do psicólogo Howard Gardner'
    print('~' * tam)
    print('\033[44m|' + f'{txt1:^{tam - 2}}|'+'\033[0;0m')
    print('~' * tam)
    print('\033[44m|' + f'{txt2:^{tam - 2}}|'+'\033[0;0m')
    aviso()

def aviso():
    tam = 133
    txt = 'Lembrando que este teste servirá apenas como base para orientar sobre quais inteligências o usuário tem maior compatibilidade'
    print('~' * tam)
    print('\033[31m' + '\033[47m|' +  f'{txt:^{tam - 2}}|'+'\033[0;0m')
    print('~' * tam)
    print()
    txt = 'A seguir você deverá escrever de 0 a 5 o quanto você concorda com cada frase'
    print(f'|{txt:^{tam - 2}}|')
    print()

#ZERAR VALORES DE OCORRÊNCIAS
for i in BD:
      i["OCORRENCIAS"]=0
      i["PERCENTUAL"]=0
  
    
cabecalho()

for pos2, i2 in enumerate(perguntas):
    print("~" * 133)
    contador = f'Questão {pos2 + 1}'
    print(f'|{contador:^{131}}|')
    caracteristica = i2["PERGUNTA"]
    print(f'|{caracteristica:^{133 - 2}}|')
    
    while True:
        try:
            nivel = int(input("O quanto você concorda com essa frase? (0/5): "))
            if 0 <= nivel <= 5:
                break
            print("Valor deve estar entre 0 e 5")
        except ValueError:
            print("Digite apenas valores inteiros")
        
    print("~" * 133)
    for pos,i in enumerate(BD):
        inteligencia=i["INTELIGENCIA"]
        caracteristicas=i["CARACTERISTICAS"]
        if (caracteristica in caracteristicas):
            i["OCORRENCIAS"]+=caracteristicas[caracteristica] * nivel
            print('Essa característica é referente à inteligência ' + '\033[32m' + inteligencia + '\033[0;0m')
print("~" * 133)        
 
#Apenas utilizado para testar as somas e conferir os resultados
#print("\nPONDERACOES")
#for i in BD:
#    print("\nINTELIGENCIA: ", i["INTELIGENCIA"], "OCORRENCIAS: ", i["OCORRENCIAS"])
    
#TOTALIZAR PESOS
for i in BD:
    caracteristicas = i["CARACTERISTICAS"]
    soma = 0
    media_ponderada = 0
    for j in caracteristicas:
        soma += caracteristicas[j]
    media_ponderada = i["OCORRENCIAS"] / soma
    i["PERCENTUAL"] = media_ponderada * 10
    
#ordenando a lista BD pelo valor dos percentuais
BD_ordenado = sorted(BD, key=lambda x: x["PERCENTUAL"], reverse=True)

# Mostrando os três maiores valores que correspondem suas possíveis inteligências
txt1 = 'Seus resultados'
print()
print('\033[44m|' + f'{txt1:^{131}}|'+'\033[0;0m')
print()
for i in range(3):
    print("~" * 133)     
    print('\033[32m' + BD_ordenado[i]["INTELIGENCIA"] + '\033[0;0m', ": %", format(BD_ordenado[i]["PERCENTUAL"], ".2f"))
    print("Informações sobre a inteligência:")
    txt = BD_ordenado[i]["DESCRICAO"]
    quebra_linhas(txt)
    print("Melhor forma de aprendizado: ", BD_ordenado[i]["APRENDIZADO"])
    print("Melhores profissões: ", BD_ordenado[i]["PROFISSOES"])
print("~" * 133) 
    
    

